

          <h2 class="sub-header">Inserir Produto</h2>

          <form action="<?=base_url()?>/cadastro" method="POST">
          <div class="form-group">
            <label for="prodInput">Nome do Produto</label>
            <input type="text" class="form-control" name="nomeProd" id="prodInput" placeholder="ex:celular">
          </div>
          <div class="form-group">
            <label for="descInput">Descrição</label>
            <input type="text" class="form-control" name="descricao" id="descInput" placeholder="Descricao">
          </div>

          <div class="form-group">
            <label for="precoInput">Preço</label>
            <input type="tel"  required="required" class="form-control"  maxlength="15"  name="preco" id="precoInput" pattern="([0-9]{1,3}\.)?[0-9]{1,3},[0-9]{2}$" placeholder="R$:00,00">
          </div>

          <div class="form-group">
            <label for="imagemInput">Imagem</label>
            <input type="text" class="form-control" id="imagemInput"  name="imagem" placeholder="imagem">
          </div>

          <button type="submit" class="btn btn-success">Salvar</button>
          <div class="btn-group">
            <a
            href="/loja"
            type="button"
            class="btn btn-default dropdown-toggle btn-warning"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">
             Retornar a lista
            </a>

          </div>
        </form>
