


          <!-- Single button -->
        <div class="btn-group">
          <button
          type="button"
          class="btn btn-default dropdown-toggle btn-success"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
            Salvar
          </button>

        </div>

          <!-- Single button -->
        <div class="btn-group">
          <button
          type="button"
          class="btn btn-default dropdown-toggle "
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
           Salvar e Fechar
          </button>

        </div>

          <!-- Single button -->
        <div class="btn-group">
          <a
          href="<?=base_url()?>/"
          type="button"
          class="btn btn-default dropdown-toggle btn-danger"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
           Cancelar
          </a>

        </div>

          <h2 class="sub-header">Inserir Produto</h2>

          <form action="<?=base_url()?>/cadastro" method="POST">
          <div class="form-group">
            <label for="descInput">Descrição</label>
            <input type="text" class="form-control" name="descricao" id="descInput" placeholder="Descricao">
          </div>

          <div class="form-group">
            <label for="precoInput">Preço</label>
            <input type="text" class="form-control" name="preco" id="precoInput" placeholder="Preço">
          </div>

          <div class="form-group">
            <label for="imagemInput">Imagem</label>
            <input type="text" class="form-control" id="imagemInput"  name="imagem" placeholder="imagem">
          </div>

          <button type="submit" class="btn btn-default">Salvar</button>
        </form>
