


          <!-- Single button -->
        <div class="btn-group">
          <button
          type="button"
          class="btn btn-default dropdown-toggle btn-success"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
            Salvar
          </button>

        </div>

          <!-- Single button -->
        <div class="btn-group">
          <button
          type="button"
          class="btn btn-default dropdown-toggle "
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
           Salvar e Fechar
          </button>

        </div>

          <!-- Single button -->
        <div class="btn-group">
          <a
          href="<?=base_url()?>/"
          type="button"
          class="btn btn-default dropdown-toggle btn-danger"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
           Cancel
          </a>

        </div>

          <h2 class="sub-header">Editar Produtos</h2>

          <form action="<?=base_url()?>/editProduto/<?=$this->produto["id_produto"]?>" method="POST">
          <div class="form-group">
            <label for="nameInput">Descrição</label>
            <input type="text" class="form-control" name="nome" id="nameInput" placeholder="Name" value="<?=$this->produto["nome"]?>">
          </div>

          <div class="form-group">
            <label for="phoneInput">Preço</label>
            <input type="text" class="form-control" name="phone" id="phoneInput" placeholder="Email" value="<?=$this->produto["phone"]?>">
          </div>

          <div class="form-group">
            <label for="emailInput">Imagem</label>
            <input type="email" class="form-control" id="emailInput"  name="email" placeholder="Email" value="<?=$this->produto["email"]?>">
          </div>

          <button type="submit" class="btn btn-default">Salvar</button>
        </form>
