          <h2 class="sub-header">Editar Produtos</h2>

          <form action="<?=base_url()?>/editProduto/<?=$this->produto["id_produto"]?>" method="POST">
          <div class="form-group">
            <label for="descInput">Descrição</label>
              <input type="text" class="form-control" name="descricao" id="descInput" placeholder="Descricao" value="<?=$this->produto["descricao"]?>">

          </div>

          <div class="form-group">
            <label for="precoInput">Preço</label>
              <!-- <input type="text" class="form-control" name="preco" id="precoInput" placeholder="Preço"> -->
            <input type="text" class="form-control" name="preco" id="precoInput" placeholder="Preço" value="<?=$this->produto["preco"]?>">
          </div>

          <div class="form-group">
            <label for="imagemInput">Imagem</label>
            <!-- <input type="text" class="form-control" id="imagemInput"  name="imagem" placeholder="imagem"> -->
            <input type="text" class="form-control" id="imagemInput"  name="imagem" placeholder="imagem" value="<?=$this->produto["imagem"]?>">
          </div>

          <button type="submit" class="btn btn-success">Salvar</button>
          <div class="btn-group">
            <a
            href="/loja"
            type="button"
            class="btn btn-default dropdown-toggle btn-warning"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">
             Retornar a lista
            </a>
        </form>
