


          <!-- Single button -->
        <div class="btn-group">
          <a
          href="<?=base_url()?>/cadastro"
          type="button"
          class="btn btn-default dropdown-toggle btn-success"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
            + Adicionar Produto
          </a>

        </div>

          <h2 class="sub-header">Lista de Produtos</h2>
          <div class="table-responsive">
            <table class="table table-striped" id="table_material">
              <thead>
                <tr>
                  <th>Produto</th>
                  <th>Descricao</th>
                  <th>Preço</th>
                  <th>Imagem</th>
                  <th>Opções</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach ($this->produto as $key) { ?>


                <tr>
                  <td><?=$key["nome"]?></td>
                  <td><?=$key["descricao"]?></td>
                  <td><?=$key["preco"]?></td>
                  <td> <img class="img-rounded" style="width:50px;height:50px" src="data:image/jpg;base64,<?=base64_encode( $key["imagem"])?>">  </td>
                  <td>
                    <div class="btn-group" role="group">
                      <a type="button" class="btn btn-default btn-primary" href="/loja/editProduto/<?=$key["id_produto"]?>">Editar</a>
                      <a type="button" class="btn btn-default btn-danger" href="/loja/deleteProduto/<?=$key["id_produto"]?>">Deletar</a>
                      <!-- <button type="button" class="btn btn-success"   id="btnImg"  >imagem</button> -->
                      <!-- data-toggle="modal" data-target="#mdImgProd" -->

                    </div>
                  </td>
                </tr>


                <?php } ?>
              </tbody>
            </table>
          </div>
