


          <!-- Single button -->
        <div class="btn-group">
          <a
          href="<?=base_url()?>/cadastro"
          type="button"
          class="btn btn-default dropdown-toggle btn-success"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
            + Adicionar Produto
          </a>

        </div>

          <h2 class="sub-header">Lista de Produtos</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Descricao</th>
                  <th>Preço</th>
                  <th>Imagem</th>
                  <th>Opções</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach ($this->produtos as $key) { ?>


                <tr>
                  <td><?=$key["descricao"]?></td>
                  <td><?=$key["preco"]?></td>
                  <td><?=$key["imagem"]?></td>
                  <td>
                    <div class="btn-group" role="group">
                      <a type="button" class="btn btn-default btn-primary" href="/editProduto/<?=$key["id_produto"]?>">Editar</a>
                       <a type="button" class="btn btn-default btn-danger" href="/deleteProduto/<?=$key["id_produto"]?>">Deletar</a>

                    </div>
                  </td>
                </tr>
                <?php } ?>
              </tbody>
            </table>
          </div>
