<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Loja Virtual</title>



    <!-- Bootstrap core CSS -->
    <link href="<?=assets('/twitter_bootstrap/css/bootstrap.min.css')?>" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="<?=assets('/twitter_bootstrap/css/dashboard.css')?>" rel="stylesheet">




   </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Loja Virtual</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?=base_url()?>/">Dashboard</a></li>
            <li><a href="<?=base_url()?>/list">Lista de Produtos</a></li>
            <li><a href="#">Usuário</a></li>
            <li><a href="#">Ajuda</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Procurar...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Visão Geral <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Relatórios</a></li>
            <li><a href="#">Analisar</a></li>
            <li><a href="#">Exportar</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="<?=base_url()?>/">Dashboard</a></li>
            <li><a href="<?=base_url()?>/list">Lista de Produtos</a></li>
          </ul>
        </div>
       	 <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>
       	 		 <?= $this->yieldView(); ?>
       	 </div>

      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>


</body></html>
